### PR TITLE
docs: add link to jupyter notebook

### PR DESCRIPTION
**Pull request by macintoshpie**

### CODE REVIEW

**Comment by macintoshpie** [comment]
@nllong can you review this? (can't tag reviewers for some reason)

**Review by nllong — APPROVED** [review]
baller!

**Comment by nllong** [comment]
Do we have the notebook linked on the buildingsync.net website at all? Perhaps under tools? or in the blob about BSYncPy?

@macintoshpie 

https://nbviewer.jupyter.org/github/BuildingSync/schema/blob/develop/docs/notebooks/bsync_examples/Small-Office-Level-1.ipynb

**Comment by macintoshpie** [comment]
@nllong yes, we link to it here, under Guides
https://buildingsync.net/technical_resources

**Pull request merged**
